### ISSUE TITLE
0.3.1 fails to build on docs.rs

### ISSUE THREAD

**Issue by dimo414** [svartalf/hostname#12]
https://docs.rs/crate/hostname/0.3.1 [failed to build](https://docs.rs/crate/hostname/0.3.1/builds/225597) as of bc9b4bb due to ``error[E0658]: `#[doc(cfg)]` is experimental``.

**Comment by svartalf** [comment]
[Latest released version](https://docs.rs/hostname/0.4.0/hostname/index.html) fixes this issue, thanks for reporting!
