### ISSUE TITLE
wasix support

### ISSUE THREAD

**Issue by hitchho** [svartalf/hostname#19]
```cargo wasix build```
```
   Compiling hostname v0.3.1
error: Unsupported target OS! Create an issue: https://github.com/svartalf/hostname/issues/new
  --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hostname-0.3.1/src/lib.rs:81:9
   |
81 |         compile_error!("Unsupported target OS! Create an issue: https://github.com/svartalf/hostname/issues/new");
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0433]: failed to resolve: use of undeclared crate or module `sys`
   --> /home/user/.cargo/registry/src/index.crates.io-6f17d22bba15001f/hostname-0.3.1/src/lib.rs:105:5
    |
105 |     sys::get()
    |     ^^^ use of undeclared crate or module `sys`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `hostname` (lib) due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by svartalf** [comment]
Same to https://github.com/svartalf/hostname/issues/16 and the discussion at https://github.com/svartalf/hostname/pull/15 , there is nothing that can be done for this crate unless Wasix introduces some way to get the machine hostname.

Let's keep this issue open and use it as a tracking issue.

**Comment by hitchho** [comment]
https://wasix.org/docs/api-reference/wasix/resolve
would this do?

**Comment by svartalf** [comment]
@hitchhooker this looks like the opposite of what we are looking for, as it resolves a DNS hostname into IP addresses (similar to [`getaddrinfo(3)`](https://man7.org/linux/man-pages/man3/getaddrinfo.3.html), for example).

In addition, I'm not sure how to determine during the compile time that we are compiling for Wasix specifically, as there is [no such compilation target in Rust](https://doc.rust-lang.org/rustc/platform-support.html).

With all of it, it seems like there is nothing can be done to resolve this issue for now.
