### ISSUE TITLE
Add to get host-ip as well?

### ISSUE THREAD

**Issue by ivanceras** [svartalf/hostname#2]
So in linux hostname command can also show the local ip via `hostname -I`
Looking at `libc` [code](https://github.com/rust-lang/libc/blob/10ac3df1736f18393016cc585abcf5ea705d02c4/src/unix/mod.rs#L774), you can clearly see the used `gethostname` function, but I couldn't intuitively find the function for getting the local-ip only.
I'm aware that there is [local-ip](https://github.com/tcr/rust-local-ip/blob/master/src/lib.rs) crate, but it's more of a hack using regex on `ifconfig` and I doubt it's cross platform, it differs output with `hostname -I` too.  Is it appropriate to add the host-ip functionality here as well?

**Comment by willstott101** [comment]
Could this be the crate you're after? https://docs.rs/get_if_addrs/0.5.3/

**Comment by svartalf** [comment]
I feel like this is out of scope of the hostname routines, so I'm going to close this issue.
Thank you, @willstott101, for providing possible alternative for the host ip stuff.
