### ISSUE TITLE
SetComputerNameExW missing NUL terminator

### ISSUE THREAD

**Issue by kornelski** [svartalf/hostname#20]
`OsStr` is not a nul-terminated string. `encode_wide()` doesn't add a terminator either. Therefore, `SetComputerNameExW` may end up reading past the buffer.

```rust
pub fn set(hostname: &OsStr) -> io::Result<()> {
    let buffer = hostname.encode_wide().collect::<Vec<_>>();
    let result = unsafe {
        sysinfoapi::SetComputerNameExW(
            sysinfoapi::ComputerNamePhysicalDnsHostname,
            buffer.as_ptr(),
        )
    };
```

It needs `buffer.push(0)` before the winapi call.

**Comment by svartalf** [comment]
Fixed in e96d1fde3433f7c5ce64bdd91a1a2d0a3af35ad2, released as `v0.4.0`
