### ISSUE TITLE
Want to know more about this project

### ISSUE THREAD

**Issue by Bin-ly** [svartalf/hostname#21]
Hello, is this project still under maintenance? I would like to know the original idea of ​​this project. Is it just to get and set the host name? Have you ever considered aligning the Linux hostname command function?

**Comment by svartalf** [comment]
Hi, @bin-ly.

Yes, this project is under low-effort maintenance and the aim is to have a Rust library, not the CLI tool. For the CLI tool, you might want to check the `coreutils` project: https://github.com/uutils/coreutils/tree/main/src/uu/hostname

**Comment by Bin-ly** [comment]
Thank you very much, I will learn about the coreutils project. Because I have been investigating rust rewriting projects recently, can I ask you if you know some work or methods to verify the security of rust rewriting projects?
