### ISSUE TITLE
Without `winapi`

### ISSUE THREAD

**Issue by Gunni** [svartalf/hostname#22]
I don't like having `winapi` and all of its nested dependencies in the lock file.

Is it possible to ... not?

I am making a linux only program so it feels like it makes sense to me.

**Comment by svartalf** [comment]
Hi, @Gunni! 

`winapi` dependency is included only if you compile your program for Windows:

https://github.com/svartalf/hostname/blob/v0.3.1/Cargo.toml#L26-L27

It still will be present in your lock file, as it is the expected Cargo behavior, but it will not be used at all.

**Comment by Gunni** [comment]
That's annoying but nothing you can do i guess.
