### ISSUE TITLE
Broken build on Windows because of loose versions in dependency tree

### ISSUE THREAD

**Issue by saarw** [svartalf/hostname#3]
The problem isn't directly in this crate, but will probably require a dependency version upgrade to be fixed.

This crate depends on winutil 0.1 that depends on versions of kernel32-sys and advapi32-sys that do not have version restrictions on the winapi crate. Now a new version of winapi has been published and that breaks the build chain. The fix is probably to upgrade the dependencies of winutil to depend on versions of kernel32-sys and advapi32-sys that fix the versions of winapi, but that will require this crate to upgrade its dependency on winutil. 

I've notified the author of winutil to the problem and got the response "Thanks for the heads up, will take a look at fixing it when I get a minute. Might be a week or so."

**Comment by DaveLancaster** [comment]
Hi, winutil should now be fixed with a version bump. I have yanked the old version due to the broken dependencies.

**Comment by fengcen** [comment]
Update cargo dependencies. It should be fixed.
