### ISSUE TITLE
Handing over crates.io name

### ISSUE THREAD

**Issue by mainrs** [svartalf/hostname#7]
Would you be ok with handing over the hostname crate name? 
[This](https://github.com/rust-crates/abandoned) is a Github repo specifically made for this. You can, however, directly transfer ownership to @lunaryorn. He made some effort to stabilise the Windows implementation already. :smile:

**Comment by swsnr** [comment]
As far as I am concerned I have no interest in taking ownership of this code, and I do not need the crates.io name.  My implementation is independent and available on crates.io as `gethostname`.

**Edit:** I think I should also clarify that this request was not made on my behalf.

@SirWindfield I'd like to have a few private words with you about this ticket, but I did not find means to contact you.  Would you mind to send me a mail at sebastian@swsnr.de?

**Comment by mainrs** [comment]
It's not about the code. hostname has been pulled a lot of times and I just think that providing them with updates is only fair for the users. And getting ownership of a crates.io name is common practice. But in the end it's up to you. I just don't see any use in having two crates that basically are the same code where one is abandoned. 

Edit: ah, looks like I missed that you are not the same guy who offered to take full ownership of the crate. I thought you just fixed the code but you started all over. My bad, sorry for the inconvenience.

**Comment by swsnr** [comment]
> ah, looks like I missed that you are not the same guy who offered to take full ownership of the crate. I thought you just fixed the code but you started all over. My bad, sorry for the inconvenience.

I must admit I was somewhat surpised to see such a request being made on my behalf, but I see that it's been a misunderstanding, so no offense taken :)

I'm aware that transferring ownership is common, but I guess in this case the ship's sailed; in any case the author of this crate can still yank their crate from crates.io if they want.  

That said, if offered to my I'd take ownership of the name, but I'd just publish a dummy crate with the same API that depends on `gethostname` and marks all it's exported members as deprecated;  I don't think there's need for both names.

**Comment by mainrs** [comment]
> I don't think there's need for both names.

That was my point too! I just didn't pay enough attention to the names, sorry :)

**Comment by swsnr** [comment]
Again no offence taken!  Thanks for writing me but I’m happy to say that things are settled now 🙂
